# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cistern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cistern_type', models.CharField(choices=[('box', 'куб'), ('hc', 'горизонтальный цилиндр'), ('vc', 'вертикальный цилиндр')], max_length=3)),
                ('name', models.CharField(default='', max_length=20)),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_time', models.DateTimeField()),
                ('add', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cistern_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fuel_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('delete', models.BooleanField(default=False)),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Device')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='DayLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cur_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='KeyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('car', models.CharField(default='', max_length=40)),
                ('keys', models.CharField(max_length=16, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MonthLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cur_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('key_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company_admin.KeyOwner')),
            ],
        ),
        migrations.CreateModel(
            name='UpDosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_admin.CompanyUser')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='WeekLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cur_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('key_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company_admin.KeyOwner')),
            ],
        ),
        migrations.AddField(
            model_name='daylimit',
            name='key_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company_admin.KeyOwner'),
        ),
        migrations.AddField(
            model_name='database',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_admin.KeyOwner'),
        ),
        migrations.AddField(
            model_name='cistern',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_admin.FuelType'),
        ),
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together=set([('name', 'company')]),
        ),
    ]
