# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Device'),
        ),
        migrations.AlterField(
            model_name='updosed',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_admin.Device'),
        ),
    ]
