# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0002_auto_20170605_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylimit',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monthlimit',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weeklimit',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
