# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0003_auto_20170606_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daylimit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monthlimit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weeklimit',
            name='id',
        ),
        migrations.AlterField(
            model_name='daylimit',
            name='key_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_admin.KeyOwner'),
        ),
        migrations.AlterField(
            model_name='monthlimit',
            name='key_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_admin.KeyOwner'),
        ),
        migrations.AlterField(
            model_name='weeklimit',
            name='key_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_admin.KeyOwner'),
        ),
    ]
