# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0004_auto_20170606_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyowner',
            name='keys',
            field=models.CharField(max_length=16),
        ),
    ]
