# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_admin', '0002_remove_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.PositiveIntegerField(default=9090, max_length=6),
        ),
    ]
